name: Publish to PyPI

on:
  push:
    tags:
      - v*

jobs:
  publish-pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: pip
      - name: Install dependencies
        run: |
          pip install --upgrade build twine
      - name: Build distribution
        run: |
          python -m build
      - name: Upload to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
