name: Test python package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: pipenv
      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev
      - name: Run tests
        run: |
          pipenv run pytest -vvvv -s
