name: Test python package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-python:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          python-version:
            - 3.11
            - 3.12
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pipx install pipenv
          pipenv install --dev --python ${{ steps.setup-python.outputs.python-path }}
      - name: Run tests
        run: |
          pipenv run pytest -vvvv -s
