name: Test python package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-python:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          python-version:
            - 3.11
            - 3.12
          logger:
            - syslog-ng
            - rsyslog
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install logger
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.logger }}
      - name: Setup python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install python dependencies
        run: |
          pipx install pipenv
          pipenv install --dev --python ${{ steps.setup-python.outputs.python-path }}
      - name: Show OpenSSL ciphers
        run: |
          openssl ciphers -v
          pipenv run python -c "import ssl; import pprint; ctx = ssl.create_default_context(); ctx.set_ciphers('ALL:@SECLEVEL=0'); pprint.pprint(ctx.get_ciphers())"
      - name: Run tests
        run: |
          pipenv run pytest -vvvv -s
